/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetointegrador.view;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import projetointegrador.dao.ClientesDAO;
import projetointegrador.model.Enderecos;
import projetointegrador.dao.EnderecosDAO;
import projetointegrador.model.Clientes;

/**
 *
 * @author willian.falcao
 */
public class FrmClientes extends javax.swing.JFrame {
    
    //listar todos os clientes que ha no banco de dados
    private void listarClientes() {
        ClientesDAO dao = new ClientesDAO();
        
        List<Clientes> lista = dao.listarClientes();
        
        DefaultTableModel tabela = (DefaultTableModel) jTableClientes.getModel();
        
        tabela.setNumRows(0);
        
        for(Clientes cliente: lista){
            tabela.addRow(new Object[]{
                cliente.getId(),
                cliente.getNome(),
                cliente.getEmail(),
                cliente.getCpf(),
                cliente.getTelefone()
            } );
        }
    }
    
    //para fazer uma busca no sistema com resultados do que o usuario digitar
    private void listarClientes(String busca) {
        ClientesDAO dao = new ClientesDAO();
        
        List<Clientes> lista = dao.listarClientes(busca);
        
        DefaultTableModel tabela = (DefaultTableModel) jTableClientes.getModel();
        
        tabela.setNumRows(0);
        
        for(Clientes cliente: lista){
            tabela.addRow(new Object[]{
                cliente.getId(),
                cliente.getNome(),
                cliente.getEmail(),
                cliente.getCpf(),
                cliente.getTelefone()
            } );
        }
    }
    
    /**
     * Creates new form TelaClientes
     */
    public FrmClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPaneClientes = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        TextFieldNomeCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TextFieldEmailCliente = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TextFieldCPFCliente = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        TextFieldTelefoneCliente = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jTabbedPaneEnderecos = new javax.swing.JTabbedPane();
        jPanelEndereco1 = new javax.swing.JPanel();
        TextFieldNumeroEndereco1 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        TextFieldBairroEndereco1 = new javax.swing.JTextField();
        jComboBoxUfEndereco1 = new javax.swing.JComboBox<>();
        jLabel46 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        TextFieldCidadeEndereco1 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        TextFieldRuaEndereco1 = new javax.swing.JTextField();
        TextFieldCepEndereco1 = new javax.swing.JFormattedTextField();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        TextFieldComplementoEndereco1 = new javax.swing.JFormattedTextField();
        jPanelEndereco2 = new javax.swing.JPanel();
        TextFieldNumeroEndereco2 = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        TextFieldBairroEndereco2 = new javax.swing.JTextField();
        jComboBoxUfEndereco2 = new javax.swing.JComboBox<>();
        jLabel52 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        TextFieldCidadeEndereco2 = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        TextFieldRuaEndereco2 = new javax.swing.JTextField();
        TextFieldCepEndereco2 = new javax.swing.JFormattedTextField();
        jLabel55 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        TextFieldComplementoEndereco2 = new javax.swing.JFormattedTextField();
        jPanelEndereco3 = new javax.swing.JPanel();
        TextFieldNumeroEndereco3 = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        TextFieldBairroEndereco3 = new javax.swing.JTextField();
        jComboBoxUfEndereco3 = new javax.swing.JComboBox<>();
        jLabel58 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        TextFieldCidadeEndereco3 = new javax.swing.JTextField();
        jLabel60 = new javax.swing.JLabel();
        TextFieldRuaEndereco3 = new javax.swing.JTextField();
        TextFieldCepEndereco3 = new javax.swing.JFormattedTextField();
        jLabel61 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        TextFieldComplementoEndereco3 = new javax.swing.JFormattedTextField();
        jLabelClientId = new javax.swing.JLabel();
        TextFieldIdCliente = new javax.swing.JTextField();
        jButtonListarEnderecos = new javax.swing.JButton();
        jButtonCadastrar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableClientes = new javax.swing.JTable();
        TextFieldBuscaCliente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButtonBuscarClientes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Cadastro de Clientes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(265, 265, 265))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jTabbedPaneClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPaneClientesMouseClicked(evt);
            }
        });

        jLabel2.setText("CPF:");

        jLabel3.setText("E-Mail:");

        jLabel4.setText("Nome:");

        try {
            TextFieldCPFCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TextFieldCPFCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldCPFClienteActionPerformed(evt);
            }
        });

        jLabel5.setText("Telefone:");

        try {
            TextFieldTelefoneCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("+## (##) #########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TextFieldTelefoneCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldTelefoneClienteActionPerformed(evt);
            }
        });

        jLabel6.setText("Dados de Contato");

        jLabel7.setText("Dados de Residência");

        jTabbedPaneEnderecos.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        TextFieldNumeroEndereco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNumeroEndereco1ActionPerformed(evt);
            }
        });

        jLabel45.setText("Bairro");

        TextFieldBairroEndereco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldBairroEndereco1ActionPerformed(evt);
            }
        });

        jComboBoxUfEndereco1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RO", "AC", "AM", "RR", "PA", "AP", "TO", "MA", "PI", "CE", "RN", "PB", "PE", "AL", "SE", "BA", "MG", "ES", "RJ", "SP", "PR", "SC", "RS", "MS", "MT", "GO", "DF" }));

        jLabel46.setText("Cidade");

        jLabel28.setText("UF:");

        jLabel47.setText("Rua:");

        jLabel48.setText("CEP:");

        try {
            TextFieldCepEndereco1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TextFieldCepEndereco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldCepEndereco1ActionPerformed(evt);
            }
        });

        jLabel49.setText("Número:");

        jLabel50.setText("Complemento:");

        try {
            TextFieldComplementoEndereco1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("?")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TextFieldComplementoEndereco1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldComplementoEndereco1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEndereco1Layout = new javax.swing.GroupLayout(jPanelEndereco1);
        jPanelEndereco1.setLayout(jPanelEndereco1Layout);
        jPanelEndereco1Layout.setHorizontalGroup(
            jPanelEndereco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEndereco1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEndereco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEndereco1Layout.createSequentialGroup()
                        .addGroup(jPanelEndereco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEndereco1Layout.createSequentialGroup()
                                .addComponent(jLabel49)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TextFieldNumeroEndereco1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelEndereco1Layout.createSequentialGroup()
                                .addComponent(jLabel50)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TextFieldComplementoEndereco1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelEndereco1Layout.createSequentialGroup()
                                .addComponent(jLabel48)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TextFieldCepEndereco1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(jPanelEndereco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEndereco1Layout.createSequentialGroup()
                                .addComponent(jLabel46)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TextFieldCidadeEndereco1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelEndereco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanelEndereco1Layout.createSequentialGroup()
                                    .addComponent(jLabel45)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(TextFieldBairroEndereco1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelEndereco1Layout.createSequentialGroup()
                                    .addComponent(jLabel47)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(TextFieldRuaEndereco1))))
                        .addGap(36, 36, 36))
                    .addGroup(jPanelEndereco1Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxUfEndereco1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(483, Short.MAX_VALUE))))
        );
        jPanelEndereco1Layout.setVerticalGroup(
            jPanelEndereco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEndereco1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelEndereco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldCepEndereco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel48)
                    .addComponent(jLabel46)
                    .addComponent(TextFieldCidadeEndereco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanelEndereco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(jLabel47)
                    .addComponent(TextFieldRuaEndereco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldComplementoEndereco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEndereco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45)
                    .addComponent(TextFieldBairroEndereco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel49)
                    .addComponent(TextFieldNumeroEndereco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanelEndereco1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxUfEndereco1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPaneEnderecos.addTab("Endereço 1", jPanelEndereco1);

        TextFieldNumeroEndereco2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNumeroEndereco2ActionPerformed(evt);
            }
        });

        jLabel51.setText("Bairro");

        TextFieldBairroEndereco2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldBairroEndereco2ActionPerformed(evt);
            }
        });

        jComboBoxUfEndereco2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RO", "AC", "AM", "RR", "PA", "AP", "TO", "MA", "PI", "CE", "RN", "PB", "PE", "AL", "SE", "BA", "MG", "ES", "RJ", "SP", "PR", "SC", "RS", "MS", "MT", "GO", "DF" }));

        jLabel52.setText("Cidade");

        jLabel29.setText("UF:");

        jLabel53.setText("Rua:");

        jLabel54.setText("CEP:");

        try {
            TextFieldCepEndereco2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TextFieldCepEndereco2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldCepEndereco2ActionPerformed(evt);
            }
        });

        jLabel55.setText("Número:");

        jLabel56.setText("Complemento:");

        try {
            TextFieldComplementoEndereco2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("?")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TextFieldComplementoEndereco2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldComplementoEndereco2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEndereco2Layout = new javax.swing.GroupLayout(jPanelEndereco2);
        jPanelEndereco2.setLayout(jPanelEndereco2Layout);
        jPanelEndereco2Layout.setHorizontalGroup(
            jPanelEndereco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEndereco2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEndereco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEndereco2Layout.createSequentialGroup()
                        .addGroup(jPanelEndereco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEndereco2Layout.createSequentialGroup()
                                .addComponent(jLabel55)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TextFieldNumeroEndereco2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelEndereco2Layout.createSequentialGroup()
                                .addComponent(jLabel56)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TextFieldComplementoEndereco2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelEndereco2Layout.createSequentialGroup()
                                .addComponent(jLabel54)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TextFieldCepEndereco2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(jPanelEndereco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEndereco2Layout.createSequentialGroup()
                                .addComponent(jLabel52)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TextFieldCidadeEndereco2, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelEndereco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanelEndereco2Layout.createSequentialGroup()
                                    .addComponent(jLabel51)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(TextFieldBairroEndereco2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelEndereco2Layout.createSequentialGroup()
                                    .addComponent(jLabel53)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(TextFieldRuaEndereco2))))
                        .addGap(36, 36, 36))
                    .addGroup(jPanelEndereco2Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxUfEndereco2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(483, Short.MAX_VALUE))))
        );
        jPanelEndereco2Layout.setVerticalGroup(
            jPanelEndereco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEndereco2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelEndereco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldCepEndereco2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel54)
                    .addComponent(jLabel52)
                    .addComponent(TextFieldCidadeEndereco2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanelEndereco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel56)
                    .addComponent(jLabel53)
                    .addComponent(TextFieldRuaEndereco2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldComplementoEndereco2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEndereco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel51)
                    .addComponent(TextFieldBairroEndereco2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel55)
                    .addComponent(TextFieldNumeroEndereco2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanelEndereco2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxUfEndereco2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel29))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPaneEnderecos.addTab("Endereço 2", jPanelEndereco2);

        TextFieldNumeroEndereco3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldNumeroEndereco3ActionPerformed(evt);
            }
        });

        jLabel57.setText("Bairro");

        TextFieldBairroEndereco3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldBairroEndereco3ActionPerformed(evt);
            }
        });

        jComboBoxUfEndereco3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RO", "AC", "AM", "RR", "PA", "AP", "TO", "MA", "PI", "CE", "RN", "PB", "PE", "AL", "SE", "BA", "MG", "ES", "RJ", "SP", "PR", "SC", "RS", "MS", "MT", "GO", "DF" }));

        jLabel58.setText("Cidade");

        jLabel30.setText("UF:");

        jLabel59.setText("Rua:");

        jLabel60.setText("CEP:");

        try {
            TextFieldCepEndereco3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TextFieldCepEndereco3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldCepEndereco3ActionPerformed(evt);
            }
        });

        jLabel61.setText("Número:");

        jLabel62.setText("Complemento:");

        try {
            TextFieldComplementoEndereco3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("?")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TextFieldComplementoEndereco3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldComplementoEndereco3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelEndereco3Layout = new javax.swing.GroupLayout(jPanelEndereco3);
        jPanelEndereco3.setLayout(jPanelEndereco3Layout);
        jPanelEndereco3Layout.setHorizontalGroup(
            jPanelEndereco3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEndereco3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEndereco3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelEndereco3Layout.createSequentialGroup()
                        .addGroup(jPanelEndereco3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEndereco3Layout.createSequentialGroup()
                                .addComponent(jLabel61)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TextFieldNumeroEndereco3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelEndereco3Layout.createSequentialGroup()
                                .addComponent(jLabel62)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TextFieldComplementoEndereco3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelEndereco3Layout.createSequentialGroup()
                                .addComponent(jLabel60)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TextFieldCepEndereco3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(jPanelEndereco3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelEndereco3Layout.createSequentialGroup()
                                .addComponent(jLabel58)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TextFieldCidadeEndereco3, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelEndereco3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanelEndereco3Layout.createSequentialGroup()
                                    .addComponent(jLabel57)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(TextFieldBairroEndereco3, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelEndereco3Layout.createSequentialGroup()
                                    .addComponent(jLabel59)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(TextFieldRuaEndereco3))))
                        .addGap(36, 36, 36))
                    .addGroup(jPanelEndereco3Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxUfEndereco3, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(483, Short.MAX_VALUE))))
        );
        jPanelEndereco3Layout.setVerticalGroup(
            jPanelEndereco3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEndereco3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanelEndereco3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldCepEndereco3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel60)
                    .addComponent(jLabel58)
                    .addComponent(TextFieldCidadeEndereco3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanelEndereco3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel62)
                    .addComponent(jLabel59)
                    .addComponent(TextFieldRuaEndereco3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldComplementoEndereco3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelEndereco3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel57)
                    .addComponent(TextFieldBairroEndereco3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel61)
                    .addComponent(TextFieldNumeroEndereco3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanelEndereco3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxUfEndereco3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTabbedPaneEnderecos.addTab("Endereço 3", jPanelEndereco3);

        jLabelClientId.setText("Identificador:");

        TextFieldIdCliente.setEditable(false);
        TextFieldIdCliente.setText("    ");

        jButtonListarEnderecos.setText("Listar Endereços");
        jButtonListarEnderecos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarEnderecosActionPerformed(evt);
            }
        });

        jButtonCadastrar.setText("Novo Cadastro");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButton1.setText("Excluir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TextFieldEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TextFieldTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TextFieldNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(TextFieldCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelClientId)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextFieldIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jTabbedPaneEnderecos)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(jButtonListarEnderecos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(jButtonCadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEditar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabelClientId)
                    .addComponent(TextFieldIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(TextFieldCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(TextFieldEmailCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonListarEnderecos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPaneEnderecos, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCadastrar)
                    .addComponent(jButtonEditar)
                    .addComponent(jButton1)))
        );

        jTabbedPaneClientes.addTab("Cadastro de Clientes", jPanel2);

        jPanel3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel3FocusGained(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
        });
        jPanel3.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel3ComponentShown(evt);
            }
        });

        jTableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "E-Mail", "CPF", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableClientesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTableClientesMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(jTableClientes);

        jLabel8.setText("Buscar:");

        jButtonBuscarClientes.setText("Buscar");
        jButtonBuscarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarClientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextFieldBuscaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonBuscarClientes)
                .addContainerGap(165, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldBuscaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jButtonBuscarClientes))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                .addGap(78, 78, 78))
        );

        jTabbedPaneClientes.addTab("Listagem de Clientes", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jTabbedPaneClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 544, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jTabbedPaneClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextFieldCPFClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldCPFClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldCPFClienteActionPerformed

    private void TextFieldTelefoneClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldTelefoneClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldTelefoneClienteActionPerformed

    private void jButtonBuscarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarClientesActionPerformed
        //se o campo pesquisar estiver em branco, lista todos os clientes
        if(TextFieldBuscaCliente.getText().isBlank()){
            listarClientes();
        }
        else{
            listarClientes(TextFieldBuscaCliente.getText());
        }
    }//GEN-LAST:event_jButtonBuscarClientesActionPerformed

    private void jButtonListarEnderecosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarEnderecosActionPerformed
        FrmListarEnderecos telaListaEnderecos = new FrmListarEnderecos();
        telaListaEnderecos.setVisible(true);
    }//GEN-LAST:event_jButtonListarEnderecosActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        try {
            boolean textFieldsValidosCliente = true;
            if(TextFieldNomeCliente.getText().isBlank()){
                    textFieldsValidosCliente = false;
            }
            if(TextFieldCPFCliente.getText().equals("   .   .   -  ")){
                    textFieldsValidosCliente = false;
            }
            if(TextFieldEmailCliente.getText().isBlank()){
                    textFieldsValidosCliente = false;
            }
            if(TextFieldTelefoneCliente.getText().equals("+   (  )          ")){
                    textFieldsValidosCliente = false;
            }        
                
            if(textFieldsValidosCliente == true) {
                if (!TextFieldRuaEndereco1.getText().isBlank()){
                    Clientes cliente = new Clientes();
                    cliente.setNome(TextFieldNomeCliente.getText());
                    cliente.setCpf(TextFieldCPFCliente.getText());
                    cliente.setEmail(TextFieldEmailCliente.getText());
                    cliente.setTelefone(TextFieldTelefoneCliente.getText());

                    ClientesDAO dao = new ClientesDAO();
                    dao.cadastrarCliente(cliente);

                    Enderecos endereco = new Enderecos();
                    endereco.setCep(TextFieldCepEndereco1.getText());
                    endereco.setRua(TextFieldRuaEndereco1.getText());
                    endereco.setNumero(Integer.parseInt(TextFieldNumeroEndereco1.getText()));
                    endereco.setComplemento(TextFieldComplementoEndereco1.getText());
                    endereco.setBairro(TextFieldBairroEndereco1.getText());
                    endereco.setCidade(TextFieldCidadeEndereco1.getText());
                    endereco.setUf(jComboBoxUfEndereco1.getSelectedItem().toString());
                    endereco.setCliente(cliente);
                    EnderecosDAO daoEnd = new EnderecosDAO();
                    daoEnd.cadastrarEndereco(endereco);
                    
                    if (!TextFieldRuaEndereco2.getText().isBlank()){
                        Enderecos endereco2 = new Enderecos();
                        endereco2.setCep(TextFieldCepEndereco2.getText());
                        endereco2.setRua(TextFieldRuaEndereco2.getText());
                        endereco2.setNumero(Integer.parseInt(TextFieldNumeroEndereco2.getText()));
                        endereco2.setComplemento(TextFieldComplementoEndereco2.getText());
                        endereco2.setBairro(TextFieldBairroEndereco2.getText());
                        endereco2.setCidade(TextFieldCidadeEndereco2.getText());
                        endereco2.setUf(jComboBoxUfEndereco2.getSelectedItem().toString());
                        endereco2.setCliente(cliente);
                        daoEnd.cadastrarEndereco(endereco2);
                    }
                    
                    if (!TextFieldRuaEndereco3.getText().isBlank()){
                        Enderecos endereco3 = new Enderecos();
                        endereco3.setCep(TextFieldCepEndereco3.getText());
                        endereco3.setRua(TextFieldRuaEndereco3.getText());
                        endereco3.setNumero(Integer.parseInt(TextFieldNumeroEndereco3.getText()));
                        endereco3.setComplemento(TextFieldComplementoEndereco3.getText());
                        endereco3.setBairro(TextFieldBairroEndereco3.getText());
                        endereco3.setCidade(TextFieldCidadeEndereco3.getText());
                        endereco3.setUf(jComboBoxUfEndereco3.getSelectedItem().toString());
                        endereco3.setCliente(cliente);
                        daoEnd.cadastrarEndereco(endereco3);
                    }
                        
                    
                }
                else {
                    int opcao = JOptionPane.showConfirmDialog(null, "Cadastrar cliente sem endereços?", "", JOptionPane.OK_CANCEL_OPTION);
                    if (opcao == 0){
                    Clientes cliente = new Clientes();
                    cliente.setNome(TextFieldNomeCliente.getText());
                    cliente.setCpf(TextFieldCPFCliente.getText());
                    cliente.setEmail(TextFieldEmailCliente.getText());
                    cliente.setTelefone(TextFieldTelefoneCliente.getText());

                    ClientesDAO dao = new ClientesDAO();
                    dao.cadastrarCliente(cliente);
                    }
                }
            }
            else {
                JOptionPane.showMessageDialog(null, "As informações do cliente não foram preenchidas.");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jTableClientesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientesMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableClientesMouseEntered

    private void jTableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableClientesMouseClicked
        TextFieldIdCliente.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 0).toString());
        TextFieldNomeCliente.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 1).toString());
        TextFieldEmailCliente.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 2).toString());
        TextFieldCPFCliente.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 3).toString());
        TextFieldTelefoneCliente.setText(jTableClientes.getValueAt(jTableClientes.getSelectedRow(), 4).toString());
        
        jTabbedPaneClientes.setSelectedIndex(0);
    }//GEN-LAST:event_jTableClientesMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ClientesDAO dao = new ClientesDAO();
        
        Clientes cliente = new Clientes();
        cliente.setId(Integer.parseInt(TextFieldIdCliente.getText()));
        dao.deletarCliente(cliente);
        
        TextFieldCPFCliente.setText("");
        TextFieldEmailCliente.setText("");
        TextFieldNomeCliente.setText("");
        TextFieldTelefoneCliente.setText("");
        TextFieldIdCliente.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        Clientes cliente = new Clientes();
        cliente.setCpf(TextFieldCPFCliente.getText());
        cliente.setEmail(TextFieldEmailCliente.getText());
        cliente.setNome(TextFieldNomeCliente.getText());
        cliente.setTelefone(TextFieldTelefoneCliente.getText());
        cliente.setId(Integer.parseInt(TextFieldIdCliente.getText()));
        
        ClientesDAO dao = new ClientesDAO();
        dao.atualizarCliente(cliente);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jPanel3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel3FocusGained

    }//GEN-LAST:event_jPanel3FocusGained

    private void jTabbedPaneClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPaneClientesMouseClicked

    }//GEN-LAST:event_jTabbedPaneClientesMouseClicked

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel3ComponentShown
        listarClientes();
    }//GEN-LAST:event_jPanel3ComponentShown

    private void TextFieldComplementoEndereco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldComplementoEndereco1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldComplementoEndereco1ActionPerformed

    private void TextFieldCepEndereco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldCepEndereco1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldCepEndereco1ActionPerformed

    private void TextFieldBairroEndereco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldBairroEndereco1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldBairroEndereco1ActionPerformed

    private void TextFieldNumeroEndereco1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNumeroEndereco1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNumeroEndereco1ActionPerformed

    private void TextFieldNumeroEndereco2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNumeroEndereco2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNumeroEndereco2ActionPerformed

    private void TextFieldBairroEndereco2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldBairroEndereco2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldBairroEndereco2ActionPerformed

    private void TextFieldCepEndereco2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldCepEndereco2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldCepEndereco2ActionPerformed

    private void TextFieldComplementoEndereco2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldComplementoEndereco2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldComplementoEndereco2ActionPerformed

    private void TextFieldNumeroEndereco3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldNumeroEndereco3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldNumeroEndereco3ActionPerformed

    private void TextFieldBairroEndereco3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldBairroEndereco3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldBairroEndereco3ActionPerformed

    private void TextFieldCepEndereco3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldCepEndereco3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldCepEndereco3ActionPerformed

    private void TextFieldComplementoEndereco3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldComplementoEndereco3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldComplementoEndereco3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextFieldBairroEndereco1;
    private javax.swing.JTextField TextFieldBairroEndereco2;
    private javax.swing.JTextField TextFieldBairroEndereco3;
    private javax.swing.JTextField TextFieldBuscaCliente;
    private javax.swing.JFormattedTextField TextFieldCPFCliente;
    private javax.swing.JFormattedTextField TextFieldCepEndereco1;
    private javax.swing.JFormattedTextField TextFieldCepEndereco2;
    private javax.swing.JFormattedTextField TextFieldCepEndereco3;
    private javax.swing.JTextField TextFieldCidadeEndereco1;
    private javax.swing.JTextField TextFieldCidadeEndereco2;
    private javax.swing.JTextField TextFieldCidadeEndereco3;
    private javax.swing.JFormattedTextField TextFieldComplementoEndereco1;
    private javax.swing.JFormattedTextField TextFieldComplementoEndereco2;
    private javax.swing.JFormattedTextField TextFieldComplementoEndereco3;
    private javax.swing.JTextField TextFieldEmailCliente;
    private javax.swing.JTextField TextFieldIdCliente;
    private javax.swing.JTextField TextFieldNomeCliente;
    private javax.swing.JTextField TextFieldNumeroEndereco1;
    private javax.swing.JTextField TextFieldNumeroEndereco2;
    private javax.swing.JTextField TextFieldNumeroEndereco3;
    private javax.swing.JTextField TextFieldRuaEndereco1;
    private javax.swing.JTextField TextFieldRuaEndereco2;
    private javax.swing.JTextField TextFieldRuaEndereco3;
    private javax.swing.JFormattedTextField TextFieldTelefoneCliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBuscarClientes;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonListarEnderecos;
    private javax.swing.JComboBox<String> jComboBoxUfEndereco1;
    private javax.swing.JComboBox<String> jComboBoxUfEndereco2;
    private javax.swing.JComboBox<String> jComboBoxUfEndereco3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelClientId;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelEndereco1;
    private javax.swing.JPanel jPanelEndereco2;
    private javax.swing.JPanel jPanelEndereco3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPaneClientes;
    private javax.swing.JTabbedPane jTabbedPaneEnderecos;
    private javax.swing.JTable jTableClientes;
    // End of variables declaration//GEN-END:variables
}


